### ISSUE TITLE
Update the bootloader setup

### ISSUE THREAD

**Issue by msquirogac** [jdolinay/avr_debug#10]
I did an adaptation of the build system to make it compile by using the PlatformIO environment.
https://github.com/msquirogac/avr-debugger-bootloader
This way it becomes easier to customise, build and program the bootloader section to any compatible mcu.

**Comment by jdolinay** [comment]
Thanks! I integrated your changes - moved the sources to src subfolder, so that it can be built with PlatformIO and updated the eclipse project to point to the files in the new location. Now both eclipse and PlatformIO are supported.
