### ISSUE TITLE
wont install in latest vs code

### ISSUE THREAD

**Issue by geetee24** [jdolinay/avr_debug#40]
Invalid library found in C:\Users\xxxxx\Documents\Arduino\libraries\avr_debug: no headers files (.h) found in C:\Users\xxxxx\Documents\Arduino\libraries\avr_debug

Whats wrong?

**Comment by jdolinay** [comment]
Hi. I think you used the root folder of this repository (avr_debug) as the arduino library. The library is actually in this subfolder: avr_debug\arduino\library\avr-debugger. Copy just the the avr-debugger subfolder to your Documents/Arduino/libraries. 

As a result you should have C:\Users\xxxxx\Documents\Arduino\libraries\avr-debugger folder and inside this folder there should be examples and src subfolders and some files, like library.properties.

If I am wrong please provide the steps to reproduce the problem.
I just tried with VS Code 1.63.2 and Arduino 1.8.19  and the library was included without problem. 

By the way, it is easier to use the debugger in VS Code with PlatformIO (https://platformio.org/). It also does not depend on Arduino IDE which eliminates the problem with missing avr-gdb.exe.
